# Generated by Django 4.2.23 on 2025-09-11 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="date_completed",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
